# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://begolu2.github.io/fastbook//fastbook/"

git_url = "https://github.com/begolu2/fastbook/tree/master/"

def custom_doc_links(name): return None
